spring:
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 494a573a5e3cc2
    password: 8978744c57fb23
  application:
    name: EA_Project
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ea_project
    username: sami
    password: 12345
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8003
