spring:
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 2200fa28d82ae3
    password: a8c48e543263fb
  application:
    name: EA_Project
  datasource:
    url: jdbc:mysql://localhost:3306/ea_project
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8003
